### PR TITLE
Support developerToken API

### PR DESCRIPTION
**Pull request by BrandonPlank**
Supports loading from ciders custom API for the developer token. The API updates the token ever 6 hours.

### CODE REVIEW

**Comment by BrandonPlank** [comment]
Further update, The web-version of cider running on port 9000 does not have access to ipcRenderer, thus causing an error when receiving the token from cider-core. The electron version remains unaffected by this issue.

image

**Comment by BrandonPlank** [comment]
nop

**Comment by BrandonPlank** [comment]
Do not merge until ipc issue is fixed

**Comment by vapormusic** [comment]
> Supports loading from ciders custom API for the developer token. The API updates the token ever 6 hours.

app-win is not using electron, so it will be better for app-win to use the old method.

**Comment by BrandonPlank** [comment]
Crypto and I discussed it, and he wants to use the api because apparently the one currently in use is not 100% reliable unlike the api.

**Comment by BrandonPlank** [comment]
We can parse the api response in the index.js file, we just need to load the bearer token from a json which I don't think you can do from there.

**Comment by child-duckling** [comment]
> Crypto and I discussed it, and he wants to use the api because apparently the one currently in use is not 100% reliable unlike the api.

the one currently in use is subject to change and is static. Here, if it does change, we update it.

**Comment by BrandonPlank** [comment]
the point of programming is to reduce manual intervention. I already automated it using golang in a server, secured by a token per request from fyre.

**Comment by vapormusic** [comment]
Hmm, maybe add an endpoint from express would work ? We will add an /devtoken key in express server, once initialized we call a get request to /devtoken , then we will do everything in cider-base and send it back to the web-server ?

**Comment by BrandonPlank** [comment]
Yeah that would definitely work.

**Comment by BrandonPlank** [comment]
Maybe not.... if we can find a way to load the auth.json in the index.js in ciderui, it would work without needing ipc

**Comment by BrandonPlank** [comment]
Fixed it!

**Comment by BrandonPlank** [comment]
Ready to merge

**Comment by BrandonPlank** [comment]
@booploops, fyre ask that you review and merge if appropriate, he wont be able to until Wednesday.

**Pull request merged**
